### ISSUE TITLE
V1.3 Internal Review

### ISSUE THREAD

**Issue by speezy37** [CS2113-AY1819S1-T16-3/main#100]
Post your issues here

**Comment by pinjuen** [comment]
![image](https://user-images.githubusercontent.com/35758553/47801302-dbdf9380-dd68-11e8-9d5c-5b4082619239.png)
Unnecessary disclaimer

**Comment by speezy37** [comment]
Person card a bit too cluttered
- the check in time, and working wage can be hidden
