### ISSUE TITLE
Leave Application function does not account for leap years

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T16-3/main#111]
**Describe the bug**
29/2/2020 is considered an invalid calendar date even though it is actually valid because 2020 is a leap year.

**To Reproduce**
1. Type in "leave date 29/2/2020
2. Results in "Wrong date format (DD/MM/YYYY) / date has passed / invalid calendar date."

**Expected behavior**
1. Type in "leave date 29/2/2020
2. Results in "Leave application requested."

**Screenshots**
![image](https://user-images.githubusercontent.com/31233120/47905467-35a7a100-dec2-11e8-90cb-a62ccba7fa74.png)

**Additional context**

<hr>

**Reported by:** @e0201942
**Severity:** Not Specified

<sub>[original: nusCS2113-AY1819S1/pe-1#65]</sub>

**Comment by Hafizuddin-github** [comment]
Hi, the input command was in a wrong format command and also in a wrong date format.
The correct format based on the user guide is:
<img width="935" alt="screenshot 2018-11-05 at 1 49 57 pm" src="https://user-images.githubusercontent.com/35729747/47980261-cc15d580-e101-11e8-8cab-b05ec9c43121.png">

Correct date format:
<img width="426" alt="screenshot 2018-11-05 at 1 56 25 pm" src="https://user-images.githubusercontent.com/35729747/47980425-9b826b80-e102-11e8-9d75-c4a0127885c3.png">

In the case of the **correct format** entered by the user: leave date/29/02/2020
<img width="549" alt="screenshot 2018-11-05 at 1 52 20 pm" src="https://user-images.githubusercontent.com/35729747/47980320-17c87f00-e102-11e8-84d7-5c98162fdfa8.png">

The program will accept the leave application. There is no bug found, program is working as intended.
