### ISSUE TITLE
cannot login follow their instruction of user guide

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T16-3/main#114]
**Describe the bug**
cannot login follow their instruction of user guide.

**To Reproduce**
1. Go to page
2. enter the command given bu them
3.press enter
5.when login fail , also never give the correct format for login

**Expected behavior**
able to login

**Screenshots**
![image](https://user-images.githubusercontent.com/42367566/47906530-67ba0280-dec4-11e8-9de5-26961b8402f2.png)

**Additional context**

<hr>

**Reported by:** @clara1234566
**Severity:** Not Specified

<sub>[original: nusCS2113-AY1819S1/pe-1#253]</sub>

**Comment by jinyao-lee** [comment]
The cause of this issue is identical to #117 

That said, we are modifying the program to ensure that the program will load the sample Address Book rather then an empty Address Book, and will replace and update the data/AddressBook.xml accordingly.

Thank you for the report.
