### ISSUE TITLE
Do not allow users to set other users' priority levels to levels higher than their own

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T16-3/main#115]
**Please describe the problem**
An administrator can set another user to IT_UNIT priority which is higher priority than himself
![image](https://user-images.githubusercontent.com/31233120/47906521-625cb800-dec4-11e8-9203-aa076751699d.png)
![image](https://user-images.githubusercontent.com/31233120/47906556-74d6f180-dec4-11e8-97ce-8a8b56d2049c.png)

**Describe the improvement you'd like to suggest**
Only allow users to change other users to a priority level that is their own at maximum.

**Additional context**
Can be abused by 2 administrators to help each other up their priority

<hr>

**Reported by:** @e0201942
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#268]</sub>

**Comment by jinyao-lee** [comment]
Hi,

Thank you for your suggestion.

This is working as intended, and it is similar to that of #126 .

An excerpt of the reply to #126 is shown below: 

> This function is working as intended, as this application is pushed to a target company that places its trusts in it's administrators and those working in I.T. Department such that they would not misuse the privileges that are given to them.
> 
> The other reason being, that there may be instances whereby someone may be appointed as one that is required to manage the application, which will require an administrator or someone from the I.T. Unit to upgrade his priority level to the highest (one that is higher than that of an admin). However, this does not mean that those from I.T. unit are holding a higher position than the administrators in the company hierarchy.
> 
> If in the event that individuals are caught misusing the given privileges, they may risk legal action being taken against them.
