### ISSUE TITLE
Bug in setDepartment

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T16-3/main#116]
**Describe the bug**

**To Reproduce**
1. Go to 'mainWindow
2. Enter setdepartment 1 d/test xys sdfs  dfkjshdkjf sdjkfhsdkj fsdkjfhskdjf sdkjfhsdkj Management 
4. 
**Expected behavior**
Accept this input as the description of wrong format did not include this

**Screenshots**
![image](https://user-images.githubusercontent.com/32838530/47906634-a3ed6300-dec4-11e8-8cb2-6b0ebf21c7d9.png)

**Additional context**
Add any other context about the problem here.![image](https://user-images.githubusercontent.com/32838530/47906616-9cc65500-dec4-11e8-8e92-a92bcc1d9387.png)

<hr>

**Reported by:** @liu-tianhang
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#291]</sub>

**Comment by Woonhian** [comment]
Hi,
Thank you for reporting the bug. The command you have provided at the `To Reproduce` section is working as intended.
`setdepartment 1 d/test xys sdfs dfkjshdkjf sdjkfhsdkj fsdkjfhskdjf sdkjfhsdkj Management`
![image](https://user-images.githubusercontent.com/35731563/47931080-c1442080-df08-11e8-995f-db237b4f5cd6.png)

However, I have noticed that you have keyed in an extra space in between `sdfs` and `dfkjshdkjf`. For this, I've fixed the bug in my upcoming PR #129. Now the command you've provided in your screenshot should be working as intended.

![image](https://user-images.githubusercontent.com/35731563/47931256-3a437800-df09-11e8-9a1a-30bed8d98a7b.png)

Thank you for the report and look forward for our latest product, BankAB v1.4!
