### ISSUE TITLE
list command not working

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T16-3/main#117]
**Describe the bug**
list command not workingg is.

**To Reproduce**
1. Go to page enter command: list
2. they show the message list all persons
3.nothing come out,doesn not list persons

**Expected behavior**
have a person list

**Screenshots**
.
![image](https://user-images.githubusercontent.com/42367566/47906792-f464c080-dec4-11e8-8630-9f3bd7728dd3.png)

**Additional context**

<hr>

**Reported by:** @clara1234566
**Severity:** Not Specified

<sub>[original: nusCS2113-AY1819S1/pe-1#310]</sub>

**Comment by jinyao-lee** [comment]
You may have previously launched a previous AB4 .jar file (not ours), and that you have executed commands in the previous AB4 that led to generating `data/AddressBook.xml`.

As the data structures for our AddressBook.xml is different than as compared to the rest of the teams', launching the BankAddressBook.jar in a folder which contains `data/AddressBook.xml` that was generated by another AddressBook jar file will cause an exception whereby the data format is incorrect, and that an empty address book will be generated, which leads to this state.

With that said, may I know, when you launch the app, was the app already in this state where the people column is empty? Or that there were already sample persons listed in the People list?
