### ISSUE TITLE
Sort function for names in ascending order not working properly.

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T16-3/main#118]
**Describe the bug**
After sorting by name in ascending order, user with name alex is at the bottom.

**To Reproduce**
1. Enter "sort name asc"
2. Scroll to the bottom

**Expected behavior**
alex should have been sorted to the top.

**Screenshots**
![image](https://user-images.githubusercontent.com/31233120/47906977-4dccef80-dec5-11e8-9753-dea740199946.png)

**Additional context**

<hr>

**Reported by:** @e0201942
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#356]</sub>

**Comment by Woonhian** [comment]
Hi,
Thank you for reporting the bug. In my upcoming PR #129 , I've updated the sort command such that the sort command should be working properly by now.
`sort name asc`
![image](https://user-images.githubusercontent.com/35731563/47931742-b2f70400-df0a-11e8-8b50-a42d8003a18b.png)
Thank you for the report and look forward for our latest product, BankAB v1.4!
