### ISSUE TITLE
Leave command (add today date)

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T16-3/main#119]
**Describe the bug**

**To Reproduce**
1. Command "leave date/02/11/2018" (today date)
4. See error "Wrong date format (DD/MM/YYYY) / date has passed / invalid calendar date."

**Expected behavior**
Add as leave as it is today date

**Screenshots**
![image](https://user-images.githubusercontent.com/32838530/47907033-6fc67200-dec5-11e8-9a42-98c5d3142a8f.png)

<hr>

**Reported by:** @liu-tianhang
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#367]</sub>

**Comment by Hafizuddin-github** [comment]
Hi, thank you for reporting this bug. I have decided to reject the command if today's date is given. 
Error message is updated to reflect this in PR #132 .

<img width="947" alt="screenshot 2018-11-05 at 2 12 20 pm" src="https://user-images.githubusercontent.com/35729747/47980961-ed2bf580-e104-11e8-8433-85ff69ee72b1.png">
