### ISSUE TITLE
Sort function for names in descending order not working properly

### ISSUE THREAD

**Issue by cs2113-bot-feedback** [CS2113-AY1819S1-T16-3/main#120]
**Describe the bug**
When sort in descending order is used, user with name alex is sorted to the top while everyone else is sorted in proper descending order.

**To Reproduce**
1. Enter "sort name desc"
2. Look at the list.

**Expected behavior**
alex should be at the bottom.

**Screenshots**
![image](https://user-images.githubusercontent.com/31233120/47907286-e3687f00-dec5-11e8-82c1-0e45635a6a65.png)

**Additional context**

<hr>

**Reported by:** @e0201942
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#403]</sub>

**Comment by speezy37** [comment]
Same issue as #118
