### ISSUE TITLE
For check ic command mode was correct but in wrong case

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T16-3/main#121]
**Describe the bug**
The mode input by user was in upper case but the app does not accept command.

**To Reproduce**
1. Type in command " check ic/S1234567E pwd/Password m/IN "

**Expected behavior**
The app should accept the mode since the input word was accurate and was the format given in the user guide

**Screenshots**

**Additional context**

<hr>

**Reported by:** @chokxy
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#433]</sub>

**Comment by speezy37** [comment]
> **Expected behavior**
> The app should accept the mode since the input word was accurate and was the format given in the user guide


![image](https://user-images.githubusercontent.com/18255748/47961123-68c36f00-e03f-11e8-91ed-54eb5bdae19e.png)

![image](https://user-images.githubusercontent.com/18255748/47961139-c0fa7100-e03f-11e8-9f30-fcd0db474550.png)
