### ISSUE TITLE
sort command after a find command

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T16-3/main#122]
**Describe the bug**
after using find command to list the people, using sort command only sorts the filtered address book

**To Reproduce**
1. type in "find alex charlotte"
2. type in "sort name desc"
3. only alex and charlotte will be shown and sorted

**Expected behavior**
The full addressbook of people sorted instead of the filtered address book sorted.

**Screenshots**

**Additional context**

<hr>

**Reported by:** @chokxy
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#554]</sub>

**Comment by Woonhian** [comment]
Hi,
This function is working as intended.

Probably the phrasing of the sentence is not really clear in the UserGuide. For this, I'll be updating the UserGuide in my upcoming PR #129.

Thank you for the report and look forward for our latest product, BankAB v1.4!
