### ISSUE TITLE
Sort function for department in asc/desc order not working properly

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T16-3/main#124]
**Describe the bug**
User with department a Management is sorted to the bottom during ascending order sort and sorted to the top during descending order sort.

**To Reproduce**
1. Enter "sort department asc"
2. Scroll to bottom
2. Enter "sort department desc"
3. Scroll to top

**Expected behavior**
Should be sorted at the top for ascending order sort and the bottom for descending order sort

**Screenshots**

**Additional context**

<hr>

**Reported by:** @e0201942
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#595]</sub>

**Comment by Woonhian** [comment]
Hi,
Thank you for reporting the bug. In my upcoming PR #129 , I've updated the sort command such that the sort command should be working properly by now.
`sort department asc`
![image](https://user-images.githubusercontent.com/35731563/47935417-30277680-df15-11e8-9e0a-9c029b6f9706.png)
`sort department desc`
![image](https://user-images.githubusercontent.com/35731563/47935439-433a4680-df15-11e8-9cfb-aa4324cabea3.png)
Thank you for the report and look forward for our latest product, BankAB v1.4!
