### ISSUE TITLE
Cannot approve leave for ADMINISTRATOR 

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T16-3/main#125]
**Describe the bug**

**To Reproduce**
1. create a leave for admin (leave date/20/11/2019)(under admin account)
2. cannot approve leave himself(which is ok)
3. login to higher auth (IT) cannot approve also

**Expected behavior**
I not sure what can approve leave fore admin?
If no one, probably admin should be allow to add leave?

**Screenshots**
![image](https://user-images.githubusercontent.com/32838530/47908050-6ccc8100-dec7-11e8-9212-37ee20d6061f.png)

<hr>

**Reported by:** @liu-tianhang
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#598]</sub>

**Comment by Hafizuddin-github** [comment]
Hi, the bug cannot be reproduced. I have tried creating a leave under an administrator and approving it as an IT user. The approval is successful, no error was given by the system.
Below is the screenshot of the approval:
<img width="774" alt="screenshot 2018-11-05 at 1 35 34 pm" src="https://user-images.githubusercontent.com/35729747/47979922-6248fc00-e100-11e8-9001-1323a5e99ae0.png">

The program works as intended.
