### ISSUE TITLE
Do not allow someone of lower priority level to delete someone of higher priority level

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T16-3/main#126]
**Please describe the problem**
An administrator level user can delete a IT_UNIT level user, which is supposed to be the highest priority.
![image](https://user-images.githubusercontent.com/31233120/47908299-e49aab80-dec7-11e8-86c2-ea5b14e97a81.png)
![image](https://user-images.githubusercontent.com/31233120/47908334-f419f480-dec7-11e8-8c86-49aac8344523.png)

**Describe the improvement you'd like to suggest**
Do not allow this to happen since it can be abused by users.

**Additional context**

<hr>

**Reported by:** @e0201942
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#673]</sub>

**Comment by jinyao-lee** [comment]
Hi,

Thank you for your suggestion.

This function is working as intended, as this application is pushed to a target company that places its trusts in it's administrators and those working in I.T. Department such that they would not misuse the privileges that are given to them. 

The other reason being, that there may be instances whereby someone may be appointed as one that is required to manage the application, which will require an administrator or someone from the I.T. Unit to upgrade his priority level to the highest (one that is higher than that of an admin). However, this does not mean that those from I.T. unit are holding a higher position than the administrators in the company hierarchy.

If in the event that individuals are caught misusing the given privileges, they may risk legal action being taken against them.
