### ISSUE TITLE
Internal review of DG and UG

### ISSUE THREAD

**Issue by jinyao-lee** [CS2113-AY1819S1-T16-3/main#158]
Post all issues related to DG and UG here.

**Comment by Woonhian** [comment]
![image](https://user-images.githubusercontent.com/35731563/48334480-ca19bc80-e695-11e8-98e3-bb89fbb810ff.png)
Typo on schedule

**Comment by speezy37** [comment]
![image](https://user-images.githubusercontent.com/18255748/48334489-ce45da00-e695-11e8-83c6-1f4d1c4a506a.png)

Add mode

**Comment by speezy37** [comment]
![image](https://user-images.githubusercontent.com/18255748/48334664-6774f080-e696-11e8-9621-ea82a5d3fe2d.png)

~~Might need to handle 2 decimal place~~

*Should be ok but need to mention in user guide
*Exchange rate also use more than 2 decimal place

**Comment by jinyao-lee** [comment]
![image](https://user-images.githubusercontent.com/35756209/48334913-216c5c80-e697-11e8-9c15-894650c66e97.png)

Alex Yeoh is checking Abbus's schedule, but message box prints `Your` allocated...

**Comment by speezy37** [comment]
![image](https://user-images.githubusercontent.com/18255748/48334966-4b258380-e697-11e8-9001-ba578911f383.png)

Might need to mention 'Management' is mandatory here

**Comment by Woonhian** [comment]
![image](https://user-images.githubusercontent.com/35731563/48335087-abb4c080-e697-11e8-9215-ceb2940a3546.png)
Hyperlink does not work. Most likely is because of `#editing-a-person-code-edit-code` changed to `#editing-an-employee-code-edit-code`

**Comment by Hafizuddin-github** [comment]
<img width="947" alt="screenshot 2018-11-12 at 4 30 33 pm" src="https://user-images.githubusercontent.com/35729747/48335308-50370280-e698-11e8-8194-b0132863f46a.png">

Prerequisites : User must log in as Administrator

**Comment by speezy37** [comment]
![image](https://user-images.githubusercontent.com/18255748/48335281-3bf30580-e698-11e8-9450-0e616cf7b937.png)
![image](https://user-images.githubusercontent.com/18255748/48335362-7066c180-e698-11e8-8926-dc1cbd10bfc2.png)

MODE or IN-OUT

**Comment by speezy37** [comment]
![image](https://user-images.githubusercontent.com/18255748/48335451-b4f25d00-e698-11e8-905b-93a36de8b7cd.png)

add set & view schedule for others

![image](https://user-images.githubusercontent.com/18255748/48335472-c89dc380-e698-11e8-9b4f-54cdc42b8675.png)
add set & view own schedule

**Comment by speezy37** [comment]
![image](https://user-images.githubusercontent.com/18255748/48335563-16b2c700-e699-11e8-8e1a-f0ad38072e62.png)
![image](https://user-images.githubusercontent.com/18255748/48335585-24684c80-e699-11e8-94d0-32649b4b455b.png)

TIME_START or START_TIME

**Comment by speezy37** [comment]
![image](https://user-images.githubusercontent.com/18255748/48335789-b3756480-e699-11e8-84e4-c556d6c927b2.png)

TAG & TAGS

**Comment by speezy37** [comment]
![image](https://user-images.githubusercontent.com/18255748/48335668-61344380-e699-11e8-9ef5-109bf239bbbf.png)
![image](https://user-images.githubusercontent.com/18255748/48335673-685b5180-e699-11e8-8031-b6be6291b37c.png)

PHONE NUMBER & PHONE_NUMBER

**Comment by speezy37** [comment]
![image](https://user-images.githubusercontent.com/18255748/48335721-8c1e9780-e699-11e8-939b-5913c5a94680.png)
![image](https://user-images.githubusercontent.com/18255748/48335729-95a7ff80-e699-11e8-93cb-5aae693c55ad.png)

EMAIL & EMAIL_ADDRESS

**Comment by Woonhian** [comment]
![image](https://user-images.githubusercontent.com/35731563/48335928-1cf57300-e69a-11e8-9d3e-0d59c94cdaa3.png)
Parameters can put 1 for APPROVE, the other for REJECT

**Comment by speezy37** [comment]
![image](https://user-images.githubusercontent.com/18255748/48336133-8d9c8f80-e69a-11e8-8a8c-0bfaf2d1dfd8.png)

has*

**Comment by jinyao-lee** [comment]
![image](https://user-images.githubusercontent.com/35756209/48335923-1830bf00-e69a-11e8-948e-e697d95f8061.png)

Discrepancy in UserGuide for setschedule command. Non admin users can setschedule for themselves.

**Comment by pinjuen** [comment]
![image](https://user-images.githubusercontent.com/35758553/48336206-bfadf180-e69a-11e8-8255-4db7032a4aaa.png)

can write as "default state"

**Comment by speezy37** [comment]
![image](https://user-images.githubusercontent.com/18255748/48336230-cdfc0d80-e69a-11e8-9dcc-98d54779afc5.png)

doesn't clear tags

**Comment by Hafizuddin-github** [comment]
<img width="947" alt="screenshot 2018-11-12 at 4 49 09 pm" src="https://user-images.githubusercontent.com/35729747/48336305-f257ea00-e69a-11e8-8628-80a0d7815243.png">

Change KEYWORD to any name in sample address book.

**Comment by pinjuen** [comment]
![image](https://user-images.githubusercontent.com/35758553/48336317-f7b53480-e69a-11e8-9c2f-4f8b3b8ab2b9.png)

need to specify those are rounded off

**Comment by Hafizuddin-github** [comment]
<img width="947" alt="screenshot 2018-11-12 at 4 49 09 pm" src="https://user-images.githubusercontent.com/35729747/48336465-4a8eec00-e69b-11e8-9be0-0ce5919de37b.png">

KEYWORDS change to any department in the sample

**Comment by jinyao-lee** [comment]
![image](https://user-images.githubusercontent.com/35756209/48336492-5ed2e900-e69b-11e8-9c79-db34958e4cb8.png)

Selecting an INDEX which is supposed to be for person ended up selecting the leave index as well

**Comment by jinyao-lee** [comment]
![image](https://user-images.githubusercontent.com/35756209/48336714-ecaed400-e69b-11e8-96b3-a15ed26afee9.png)

Change to edit personal particulars

![image](https://user-images.githubusercontent.com/35756209/48336730-fa645980-e69b-11e8-99e8-b318964b5937.png)
Change to edit personal particulars

**Comment by pinjuen** [comment]
![image](https://user-images.githubusercontent.com/35758553/48336794-1ff16300-e69c-11e8-80e8-f1b6d55544ff.png)

can put under one box

**Comment by speezy37** [comment]
![image](https://user-images.githubusercontent.com/18255748/48337018-bcb40080-e69c-11e8-82ad-9b8eee7bd854.png)

Remove A.1.1

**Comment by speezy37** [comment]
![image](https://user-images.githubusercontent.com/18255748/48337113-03a1f600-e69d-11e8-9296-b04a8e7f1ab0.png)

Extension for user not logged in

**Comment by Woonhian** [comment]
![image](https://user-images.githubusercontent.com/35731563/48337314-95116800-e69d-11e8-9548-6d4b9a97019f.png)
Use case shift down and there is extra use case

**Comment by pinjuen** [comment]
![image](https://user-images.githubusercontent.com/35758553/48337356-ba9e7180-e69d-11e8-87dc-8f2268af039e.png)

Index instead of ID??

**Comment by speezy37** [comment]
![image](https://user-images.githubusercontent.com/18255748/48337502-0c46fc00-e69e-11e8-85f9-ed452f367142.png)

Extension for non IT-Unit

**Comment by Hafizuddin-github** [comment]
<img width="947" alt="screenshot 2018-11-12 at 5 10 30 pm" src="https://user-images.githubusercontent.com/35729747/48337499-09e4a200-e69e-11e8-86cb-a0dc940e2924.png">

LOGIN COMMAND

missing "an" , AddressBook shows an error message.

**Comment by Hafizuddin-github** [comment]
<img width="947" alt="screenshot 2018-11-12 at 5 17 22 pm" src="https://user-images.githubusercontent.com/35729747/48337809-f4bc4300-e69e-11e8-96e1-44348e65626a.png">
ADD command
Missing "an", AddressBook shows an error message.

**Comment by Hafizuddin-github** [comment]
<img width="947" alt="screenshot 2018-11-12 at 5 20 51 pm" src="https://user-images.githubusercontent.com/35729747/48337937-52e92600-e69f-11e8-9b00-8e656098d364.png">


Missing "an"

**Comment by jinyao-lee** [comment]
![image](https://user-images.githubusercontent.com/35756209/48338072-aa879180-e69f-11e8-9a0f-16c8d173fd29.png)

**Developer Guide**
Better to be explicit about this error. Testers may become surprised as to why a valid date isn't accepted, when they didn't realize that the date has already passed

**Comment by Hafizuddin-github** [comment]
<img width="730" alt="screenshot 2018-11-12 at 5 26 28 pm" src="https://user-images.githubusercontent.com/35729747/48338256-241f7f80-e6a0-11e8-911c-db55b55b73d9.png">


Include leave.xml

**Comment by jinyao-lee** [comment]
All issues fixed. Closing issue.
